trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - script: |
      echo this is the hostname:
      echo ---------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      projectName: '$(projectName)'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '21022609-Gang_FYP_Project'
      cliProjectName: 'FYP_Project'
      cliSources: '.'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  
#  trigger:
#- dependabot/github_actions/helm/kind-action-1.7.0

  #pool:
    #vmImage: ubuntu-latest

#creating namespace

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-connection'
    command: 'create'
    arguments: 'namespace monitoring'


- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks-connection'
    namespace: 'monitoring'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'charts/kube-prometheus-stack'
    releaseName: 'prometheus'
    arguments: '--dependency-update'
  #  azureSubscriptionForACR: 'b361fd1e-96a9-4273-9b8e-cca9183ead8d'
  #  azureResourceGroupForACR: 'monitoring'
  #  azurecontainerRegistry: $(azureContainerRegistry)
    



